### ISSUE TITLE
Limb management (missing arm, robotic hand, etc) broken / non-functional

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Prospector-Station#10]

**Comment by WkSavage** [comment]
@JakeDaBoss Ill take a look into this. This is under setup_preferences in new player under mobs. Ill take a look and see if we cant update overall limb managment.

**Comment by WkSavage** [comment]
Fixed in #14

**Comment by JakeDaBoss** [comment]
Resolved by @WkSavage
