### ISSUE TITLE
No APC on mining outpost EVA

### ISSUE THREAD

**Issue by ApexSwordGuy** [JakeDaBoss/Prospector-Station#34]
https://gyazo.com/affde62096d95b8c24c5fb6c541d34b1

Why is this not here?

**Comment by WkSavage** [comment]
This is due to the wonderful developer Jamiedigweed! We want to take this moment to thank Jamie for being a g8 m8 and proving 10/10 code. On a more serious note this has been fixed in one of my many map bugfixes, or if not it is in the pull i plan on releasing later tonight.

**Comment by WkSavage** [comment]
fixed it #36
