### ISSUE TITLE
Admins getting logs is broken somehow.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Prospector-Station#38]
Invalid network address in transmission (https://check.torproject.org/exit-addresses) is the error I think is associated with it.

**Comment by ApexSwordGuy** [comment]
Might be linked, can't do player age checks currently.

**Comment by JakeDaBoss** [comment]
That's a DB issue.

**Comment by JakeDaBoss** [comment]
Also, it appears Nightspark can do this as Head Mod, but I as Host can't.

**Comment by JakeDaBoss** [comment]
Hold off on this yet, it may be my own computer.

**Comment by JakeDaBoss** [comment]
Confirmed own computer.
