### ISSUE TITLE
Holsters are broken

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Prospector-Station#7]

**Comment by WkSavage** [comment]
I have gotten Holsters to work. What guns do we /not/ want in Holsters?

**Comment by JakeDaBoss** [comment]
Syndicate weapons, larger weaponry (Shotgun, Laser Carbine)

Basically the standard stuff that realistically speaking shouldn't fit in there. Keep e-guns able, colt 1911 and taser I suppose.

Also an idea is a back sling, that you can attach to your suit, and it negates the necessity of a hardsuit, and allows you to store any weapon on your back. Syndicate + Regular use?

**Comment by JakeDaBoss** [comment]
Resolved by @WkSavage
